config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'}

  resources :products, :path=> "cats" do
    resources :products_avatars, only: [:create]
  end

  resources :users, :path=> "friends", only: [:show, :edit, :update] do
      resources :avatars, only: [:create]
  end

  namespace :admins do
    resources :admin, only: [:index]
    resources :users
    resources :products
    root to: "admin#index"
  end

  resources :carts, only: [:destroy, :create, :update, :show]
  resources :orders,  only: [:index, :create]

  resources :cart_products
  root 'home#index'
  get 'contact', to: 'home#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send



  has_one :cart
  has_many :orders
  has_one_attached :avatar

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def name
    if self.first_name && self.last_name
      self.first_name + " " + self.last_name
    else
      self.first_name
    end
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :check_if_admin


  def index
    @users = User.all
    @products = Product.all
    @orders = Order.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    user_params = params.permit(:first_name,:last_name,:description)

    if @user.update(user_params)
      redirect_to admins_users_path
      flash[:notice] = "The user was successfully modified"
    else
      render :show
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admins_users_path
  end

 private

  def check_if_admin
    redirect_to root_path unless current_user.try(:admin?)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :good_user?, only: [:show, :edit, :update]

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :user_name, :description, :email)
    end

    def good_user?
      if @user != current_user
        flash[:danger] = "You do not have access to other user account"
        redirect_to root_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user, url: user_path(user), html: { method: :patch }) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="row">
    <div class="col-md-6">
        <div class="form-group">
          <div class="field">
            <%= form.label :first_name, class: "form-control-label" %>
            <%= form.text_field :first_name, class: "form-control", placeholder: "Enter your first name" %>
          </div>
        </div>
    </div>    
    <div class="col-md-6">
      <div class="form-group">
          <%= form.label :last_name, class: "form-control-label" %>
          <%= form.text_field :last_name, class: "form-control", placeholder: "Also your last name" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
        <div class="form-group">
          <%= form.label :email, class: "form-control-label" %>
          <%= form.email_field :email, class: "form-control", placeholder: "name@exmaple.com" %>
          <small class="form-text text-muted mt-2">This is the main email address that we'll send notifications to. </small>
        </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
          <%= form.label :user_name, class: "form-control-label" %>
          <%= form.text_field :user_name, class: "form-control", placeholder: "And your user name" %>
      </div>
    </div>
  </div>

  <!-- Description -->
  <div class="pt-5 mt-5 delimiter-top">

      <div class="page-inner-header mb-4">
          <h5 class="mb-1">About me</h5>

          <p class="text-muted mb-0">Use this field to let others know you better.</p>

      </div>

      <div class="row">
          <div class="col">
              <div class="form-group">
                  <div class="form-group">
                    <div class="field">
                      <%= form.label :description, class: "form-control-label" %>
                      <%= form.text_area :description, class:"form-control", placeholder: "Tell us a few words about yourself", rows: "3" %>
                    </div>
                    <small class="form-text text-muted mt-2">You can @mention other users and organizations to link to them.</small>
                  </div>
              </div>
          </div>
      </div>
  </div>

  <div class="pt-5 mt-5 delimiter-top">
    <%= form.submit "Save changes", class: "btn btn-sm btn-primary" %>      
    <%= link_to 'Cancel', @user, class: "btn btn-link" %> 
  </div>
<% end %>

app/views/users/_nav_lateral.html.erb
<div class="col-lg-3">

    <div data-toggle="sticky" data-sticky-offset="100" data-negative-margin=".card-profile-cover">

        <div class="card">
            <%= link_to @user, class: "btn btn-icon btn-group-nav shadow btn-secondary" do %>
                <div class="card-header py-3">
                        <span class="btn-inner--icon"><i class="fas fa-user"></i></span>
                        <span class="btn-inner--text d-none d-md-inline-block">My Profile</span>
                </div>
            <% end %>

            <div class="card-header py-3">
                <span class="h6">Settings</span>
            </div>
            <div class="list-group list-group-sm list-group-flush">
                <%= link_to edit_user_path(@user), class: "list-group-item list-group-item-action d-flex justify-content-between" do  %>
                    <div>
                        <i class="fas fa-user-circle mr-2"></i>
                        <span>Profile</span>
                    </div>
                    <div>
                        <i class="fas fa-angle-right"></i>
                    </div>
                <% end %>

                <%= link_to edit_user_registration_path, class: "list-group-item list-group-item-action d-flex justify-content-between" do  %>
                    <div>
                        <i class="fas fa-cog mr-2"></i>
                        <span>Settings</span>
                    </div>
                    <div>
                        <i class="fas fa-angle-right"></i>
                    </div>
                <% end %>
                <%= link_to orders_path, class: "list-group-item list-group-item-action d-flex justify-content-between"  do%>
                    <div>
                        <i class="fas fa-credit-card mr-2"></i>
                        <span>Billing</span>
                    </div>
                    <div>
                        <i class="fas fa-angle-right"></i>
                    </div>
                <% end %>
            </div>
        </div>

    </div>

</div>

app/views/users/_small_card.html.erb
<div class="col-md-4 mb-5">

    <div data-toggle="sticky" data-sticky-offset="100" data-negative-margin=".card-profile-cover">

        <div class="card card-profile border-0 shadow  text-center">
            <div class="card-profile-cover">
                <%if @user.avatar.attached?%>
                    <%= image_tag(@user.avatar, :alt => "avatar", class: "card-img-top") %> 
                <%else%>
                    <%= image_tag("img/prv/team-1-800x800.jpg", :alt => "avatar", class: "card-img-top") %> 
                <%end%>      

            </div>
            <div>
                <%if @user.avatar.attached?%>
                    <%= image_tag(@user.avatar, :alt => "avatar", class: "card-profile-image avatar shadow") %> 
                <%else%>
                    <%= image_tag("img/prv/team-1-800x800.jpg", :alt => "avatar", class: "card-profile-image avatar shadow") %> 
                <%end%>
            </div>      

            <div class="card-body">
                <div class="mb-3">
                    <h5 class="mb-0"><%= @user.name%></h5>
                    <span class="text-muted"><%= @user.user_name %></span>
                </div>
                <span class="text-muted"><i class="fas fa-envelope mr-2"></i><%= @user.email %></span>
            </div>
        </div>

    </div>

</div>

app/views/users/edit.html.erb
<section class="slice">
    <div class="container">
        <div class="row row-grid">
            <%= render "nav_lateral" %>
            <div class="col-lg-9">
                <!-- Change avatar -->

                <div class="card bg-gradient-warning border-0 shadow mb-4">
                    <div class="card-body py-3">
                        <div class="row row-grid align-items-center">
                            <div class="col-lg-8">
                                <div class="media align-items-center">
                            <div class="avatar rounded-circle shadow">
                                        <%if @user.avatar.attached?%>
                                            <%= image_tag(@user.avatar, :alt => "avatar", class: "card-img-top") %> 
                                        <%else%>
                                            <%= image_tag("img/prv/team-1-800x800.jpg", :alt => "avatar", class: "card-img-top") %> 
                                        <%end%>      
                                    </div>
                                    <div class="media-body">
                                        <h5 class="text-white mb-0"><%= @user.first_name %></h5>
                                        <div>   
 
                                            <%= form_tag user_avatars_path(@user), multipart: true do %>
                                                <%= file_field_tag :avatar %>
                                                <%= submit_tag "uploader l'avatar", class: "text-white" %>
                                            <% end %>


                                        <% if false %>
                                        
                                            <form>
                                                <input type="file" name="file-1[]" id="file-1" class="custom-input-file custom-input-file-link" data-multiple-caption="{count} files selected" multiple />
                                                <label for="file-1">
                                                    <span class="text-white">Change avatar</span>
                                                </label>
                                            </form>
                                        <% end %>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            </div>
                    </div>
                </div>

                    <!-- General -->

                    <div class="page-inner-header mb-4">
                        <h5 class="mb-1">General information</h5>

                        <p class="text-muted mb-0">You can help us, by filling your data, create you a much better experience using our website.</p>

                    </div>

                    <%= render 'form', user: @user %>

            </div>
        </div>
    </div>
</section>

app/views/users/show.html.erb
<section class="pt-5 pt-lg-0 bg-secondary">
    <div class="container">
        <div class="row">
            <%= render "small_card" %>
            <div class="col-md-8 mt-lg-5 mb-5">
                <!-- Setting -->

                <div class="page-header mb-4">

                    <div class="row align-items-center">
                        <div class="col-md-6 mb-3 mb-md-0">
                            <%= link_to edit_user_path(@user), class: "h6 mb-0"  do %>
                              <i class="fas fa-angle-left mr-3"></i>Settings
                            <% end %>                                  
                        </div>
                        <div class="col-md-6 text-md-right">

                        </div>
                    </div>

                </div>


                <!-- General -->

                <!-- Timeline -->
                <div class="card">
                    <div class="card-header pt-4 pb-2 border-0">
                        <div class="d-flex align-items-center">
                            <div class="avatar rounded-circle shadow">
                              <%if @user.avatar.attached?%>
                                  <%= image_tag(@user.avatar, :alt => "avatar", class: "card-img-top") %> 
                              <%else%>
                                  <%= image_tag("img/prv/team-1-800x800.jpg", :alt => "avatar", class: "card-img-top") %> 
                              <%end%>      
                            </div>
                            <div class="avatar-content">
                                <h6 class="mb-0"><%= @user.name %></h6>
                                <small class="d-block text-muted"><i class="fas fa-clock mr-2"></i>Created : <%= @user.created_at %></small> 
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <p><%= @user.description %></p>
                        <!-- Badges -->
                        <div class="d-lg-flex">
                            <a class="media d-flex align-items-center mr-lg-5 mb-3 mb-lg-0">
                                <img alt="Image placeholder" src="../assets/img/icons/dusk/svg/in-progress.svg" style="width: 36px;">
                                <div class="media-body pl-2">
                                    <span class="h6">10 Skills</span>
                                </div>
                            </a>
                            <a class="media d-flex align-items-center mr-lg-5 mb-3 mb-lg-0">
                                <img alt="Image placeholder" src="../assets/img/icons/dusk/svg/natural-user-interface-1.svg" style="width: 36px;">
                                <div class="media-body pl-2">
                                    <span class="h6">57 Endorsements</span>
                                </div>
                            </a>
                            <a class="media d-flex align-items-center mb-3 mb-lg-0">
                                <img alt="Image placeholder" src="../assets/img/icons/dusk/svg/collect.svg" style="width: 36px;">
                                <div class="media-body pl-2">
                                    <span class="h6">7 Accomplishments</span>
                                </div>
                            </a>
                        </div>
                </div>
            </div>
        </div>
    </div>
</section>