config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'}

  resources :products, :path=> "cats" do
    resources :products_avatars, only: [:create]
  end

  resources :users, :path=> "friends", only: [:show, :edit, :update] do
      resources :avatars, only: [:create]
  end

  namespace :admins do
    resources :admin, only: [:index]
    resources :users
    resources :products
    root to: "admin#index"
  end

  resources :carts, only: [:destroy, :create, :update, :show]
  resources :orders,  only: [:index, :create]

  resources :cart_products
  root 'home#index'
  get 'contact', to: 'home#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_one :order
  has_many :cart_products
  has_many :products, through: :cart_products
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_action :correct_user

  # GET /carts
  # GET /carts.json

  # GET /carts/1
  # GET /carts/1.json

  def index
    @user = User.find(params[:user_id])
    @cart = @user.cart
  end

  def show
    @cart = Cart.find(params[:id])
    @total = 0
    @cart.products.each do |product|
      @total += product.price
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:user_id, :product_id, :purchased)
    end

    def correct_user
      if current_user.cart != @cart
        flash[:danger] = "Incorrect cart"
        redirect_to '/'
      end
    end
  
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_page.html.erb
<!DOCTYPE html>
<html lang="en">
    <main>
        <header class="header-account-page bg-gradient-primary d-flex align-items-end">
            <div class="container">
              <h1 class="text-white text-center mt-0" style="font-weight: bold">THP Kittens</h1>
                <div class="row">
                    <div class=" col-lg-12">
                        <div class="row align-items-center mb-4">
                            <div class="col-md-5 mb-4 mb-md-0">
                                <span class="h2 mb-0 text-white d-block">Shopping Cart</span>
                            </div>
                        </div>
                      </header>
        <section class="slice slice-lg">
            <div class="container">
                <!-- Shopping cart -->
                <div class="table-responsive">
                    <table class="table align-items-center">
                        <thead>
                            <tr>
                                <th>Product</th>
                                <th>Price</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                          <% @cart.products.each do |product| %>
                          <%= @cart.cart_products%>
                            <tr>
                                <td>
                                    <div class="media align-items-center">
                                        <img alt="Image placeholder" class="mr-3" src="<%=product.image_url%>" style="width: 100px;">
                                        <div class="media-body">
                                            <div class="lh-100">
                                                <span class="text-dark font-weight-bold mb-0"><%=product.title%></span>
                                            </div>
                                            <span class="font-weight-bold text-muted"></span>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <span class="font-weight-bold">$<%=product.price%> USD</span>
                                </td>
                                <td class="text-right">
                                  <%= link_to cart_product_path(product.id), class: "text-light", method: :delete do %>
                                                                          <i class="fas fa-times"></i>
                                    <%end%>
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
                <!-- Cart information -->
                <div class="mt-5 pt-5 delimiter-top">
                    <div class="row justify-content-center">
                        <div class="col-md-5 col-lg-4 text-center">
                            <h5 class="mb-0">Total : <%=@total%> $</h5>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="slice bg-gradient-primary">
            <span class="tongue tongue-top">
        <i class="fas fa-angle-up"></i>
    </span>
            <div class="container text-center">
                <a href="new_user_cart_charge_path" class="btn btn-white btn-circle mt-4">Place order</a>
            </div>
        </section>

    </main>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :purchased %>
    <%= form.check_box :purchased %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<!DOCTYPE html>
<html lang="en">
    <main>
        <header class="header-account-page slice slice-lg bg-gradient-warning d-flex align-items-end">
            <div class="container">
              <h1 class="text-white text-center mt-0" style="font-weight: bold">The Kitten Project</h1>
                <div class="row">
                    <div class=" col-lg-12">
                        <div class="row align-items-center mb-4">
                            <div class="col-md-5 mb-4 mb-md-0">
                                <span class="h2 mb-0 text-white d-block">Shopping Cart</span>
                            </div>
                        </div>
                      </header>

        <section class="slice slice-lg">
            <div class="container">
                <!-- Shopping cart -->
                <div class="table-responsive">
                    <table class="table align-items-center">
                        <thead>
                            <tr>
                                <th>Product</th>
                                <th>Price</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                          <% @cart.products.each do |product| %>
                            <tr>
                                <td>
                                    <div class="media align-items-center">
                                        <%if product.avatar.attached?%>
                                            <%= image_tag product.avatar, alt: 'Image placeholder', class: "mr-3", width: 50, height: 50  %>
                                        <%else%>
                                            <%= image_tag "/assets/img/brand/logo_1.png", alt: "Image placeholder", :class => "img-fluid" %>
                                        <% end %>
                                        <div class="media-body">
                                            <div class="lh-100">
                                                <span class="text-dark font-weight-bold mb-0"><%=product.title%></span>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <span class="font-weight-bold">$<%=product.price%> USD</span>
                                    </td>
                                    <td class="text-right">
                                        <%cp = CartProduct.where(cart_id: @cart.id, product_id: product.id) %>
                                      <%= link_to cart_product_path(cp.first.id), class: "text-light", method: :delete do %>
                                                                              <i class="fas fa-times"></i>
                                        <%end%>
                                    </td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                    <!-- Cart information -->
                    <div class="mt-5 pt-5 delimiter-top">
                        <div class="row justify-content-center">
                            <div class="col-md-5 col-lg-4 text-center">
                                <h5 class="mb-0"><%= @total%> $</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section class="slice slice-lg bg-gradient-warning">
                <span class="tongue tongue-top">
            <i class="fas fa-angle-up"></i>
        </span>
                <div class="container text-center">
                  <%= form_tag orders_path() do %>
                    <article>
                      <% if flash[:error].present? %>
                        <div id="error_explanation">
                          <p><%= flash[:error] %></p>
                        </div>
                      <% end %>
                      <label class="amount">
                        <span>Amount : <%= @total%> $</span>
                      </label>
                    </article>

                    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                            data-description="A month's subscription"
                            data-amount="<%= @total * 100%>"
                            data-locale="auto"></script>
                  <% end %>
                </div>

            </section>

        </main>