config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'}

  resources :products, :path=> "cats" do
    resources :products_avatars, only: [:create]
  end

  resources :users, :path=> "friends", only: [:show, :edit, :update] do
      resources :avatars, only: [:create]
  end

  namespace :admins do
    resources :admin, only: [:index]
    resources :users
    resources :products
    root to: "admin#index"
  end

  resources :carts, only: [:destroy, :create, :update, :show]
  resources :orders,  only: [:index, :create]

  resources :cart_products
  root 'home#index'
  get 'contact', to: 'home#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  validates :price,
        presence: true,
        numericality: {greater_than: 0}
  validates :title,
        presence: true,
        length: { in: 3..30, message: "must be between 3 and 30 characters" }
  validates :description,
        presence: true,
        length: {in: 15..600, message: "must be between 20 and 600 characters"}


  has_many :cart_products, dependent: :destroy
  has_one_attached :avatar
end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController

  def index
    @users = User.all
    @products = Product.all
    @orders = Order.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    product_params = params.permit(:title, :description, :price)

    if @product.update(product_params)
      @product.avatar.attach(params[:avatar])
      flash[:notice] = "The product was successfully modified"
      redirect_to admins_products_path
    else
      render :show
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admins_root_path
  end

 private

  def check_if_admin
    redirect_to root_path unless current_user.try(:admin?)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @products = Product.all
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:price, :name)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_big_cards_product.html.erb
    <!--START-->

    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <img src="https://cdn.pixabay.com/photo/2017/12/29/20/08/eye-3048526_960_720.jpg" alt="product">
                <div class="card-body">
                    <h5 class="heading heading-5 strong-600">Title</h5>
                    <h6 class="text-muted mb-4">description</h6>
                    <p class="card-text">description balblabla</p>
                    <h6 class="text-muted mb-4">Price</h6>
                    <p class="card-text">$$$$$$$</p>
                    <a href="#" class="btn center btn-sm btn-primary">Add to cart</a>
                </div>
            </div>
        </div>
    </div>

    <!--END-->

    

app/views/products/_cards_product.html.erb
    <!--START-->

    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="https://cdn.pixabay.com/photo/2014/03/29/09/17/cat-300572_960_720.jpg"
            alt="Card image cap" class="img-fluid">
        <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Some quick example text....</p>
            <h5>Price</h5>
            <p>The price</p>
            <button type="button" class="btn btn-secondary btn-icon-label">
                <span class="btn-inner--icon"><i class="fas fa-shopping-cart"></i></span>
                <span class="btn-inner--text">Add to cart</span>
            </button>
        </div>
    </div>

    <!--END-->

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product_index.html.erb
<div class="col-lg-3 col-sm-6 col-sm-6 mb-5">
    <div class="card card-product no-border shadow shadow--hover">

        <div class="card-image">
            <%if product.avatar.attached?%>
                <%= link_to product_path(product.id) do  %>
                    <%= image_tag product.avatar, alt: 'cat', height: 308, width: 308%>
                <% end %>
            <%else%>
                <%= link_to product_path(product.id) do %>
                    <%= image_tag "/assets/img/brand/logo_1.png", alt: "Image placeholder", :class => "img-fluid" %>
                <% end %>
            <%end%>
            <span class="ribbon ribbon-right ribbon-primary rounded-circle">New</span>
        </div>
        <div class="card-body pt-0 text-center">
            <%= link_to product_path(product.id), :class => "card-title" do%>
                <%= product.title %>
            <% end %>

            <span class="card-price">$<%=product.price%> USD</span>
            <div class="product-colors mt-3">
                <a href="#" style="background-color: #59ad46;" data-toggle="tooltip" data-original-title="Green"></a>
                <a href="#" style="background-color: #04050a;" data-toggle="tooltip" data-original-title="Black"></a>
                <a href="#" style="background-color: #62aedd;" data-toggle="tooltip" data-original-title="Blueish"></a>
                <a href="#" style="background-color: #e84385;" data-toggle="tooltip" data-original-title="Pink"></a>
            </div>
        </div>
        <div class="card-product-actions" data-animation-in="slideInLeft" data-animation-out="slideOutLeft">
            <button type="button" class="btn-product-action" data-toggle="tooltip" data-original-title="Add to cart">
                <i class="fas fa-shopping-bag"></i>
            </button>
            <button type="button" class="btn-product-action" data-toggle="tooltip" data-original-title="Wishlist">
                <i class="fas fa-heart"></i>
            </button>
        </div>
    </div>
</div>

app/views/products/_product_partial.html.erb
<div class="col-lg-3 col-sm-6 col-sm-6 mb-5">
    <div class="card card-product no-border shadow shadow--hover">

        <div class="card-image">
            <%if product.avatar.attached?%>
                <%= link_to product_path(product.id) do  %>
                    <%= image_tag product.avatar, alt: 'cat', height: 208, width: 208%>
                <% end %>
            <%else%>
                <%= link_to product_path(product.id) do %>
                    <%= image_tag "/assets/img/brand/logo_1.png", alt: "Image placeholder", :class => "img-fluid" %>
                <% end %>
            <%end%>
            <span class="ribbon ribbon-right ribbon-primary rounded-circle">New</span>
        </div>
        <div class="card-body pt-0 text-center">
            <%= link_to product_path(product.id), :class => "card-title" do%>
                <%= product.title %>
            <% end %>

            <span class="card-price">$<%=product.price%> USD</span>
            <div class="product-colors mt-3">
                <a href="#" style="background-color: #59ad46;" data-toggle="tooltip" data-original-title="Green"></a>
                <a href="#" style="background-color: #04050a;" data-toggle="tooltip" data-original-title="Black"></a>
                <a href="#" style="background-color: #62aedd;" data-toggle="tooltip" data-original-title="Blueish"></a>
                <a href="#" style="background-color: #e84385;" data-toggle="tooltip" data-original-title="Pink"></a>
            </div>
        </div>
        <div class="card-product-actions" data-animation-in="slideInLeft" data-animation-out="slideOutLeft">
            <button type="button" class="btn-product-action" data-toggle="tooltip" data-original-title="Add to cart">
                <i class="fas fa-shopping-bag"></i>
            </button>
            <button type="button" class="btn-product-action" data-toggle="tooltip" data-original-title="Wishlist">
                <i class="fas fa-heart"></i>
            </button>
        </div>
    </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="row">
    <%@products.each do |product|%>
        <%= render "products/product_index", product: product %>
    <%end%>
</div>

<br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%= stylesheet_link_tag "products", media: "all" %>
<section class="slice slice-lg" id="sct-products">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <!-- Product gallery -->
                <div class="mb-5 imgProd">
                    <%if @product.avatar.attached?%>
                        <%= link_to product_path(@product.id) do  %>
                            <%= image_tag @product.avatar, alt: 'cat', height: 550, width: 550%>
                        <% end %>
                    <%else%>
                        <%= link_to product_path(@product.id) do  %>
                            <img alt="Image placeholder" src="/assets/img/brand/logo_1.png" class="img-fluid">
                            <% end %>
                    <%end%>
                </div>

            </div>
            <div class="col-lg-6">
                <form class="pl-lg-4">
                    <!-- Product title -->
                    <h2 class="h5 text-capitalize"><%=@product.title%></h2>

                    <!-- Rating stars -->

                    <span class="static-rating static-rating-sm">

                        <i class="star fas fa-star voted"></i>
                        <i class="star fas fa-star voted"></i>
                        <i class="star fas fa-star voted"></i>
                        <i class="star fas fa-star voted"></i>
                        <i class="star fas fa-star"></i>

                    </span>


                    <!-- Product description -->
                    <div class="mt-4">
                        <small class="text-dark font-weight-bold d-block mb-2">Description:</small>
                        <p class="text-sm lh-150"><%=@product.description%></p>
                    </div>

                    <!-- Size -->
                    <div class="mt-4">
                        <small class="d-block font-weight-bold text-dark mb-2">Size:</small>
                        <div class="d-flex justify-content-between">
                            <div class="checkbox">
                                <input id="size-1" name="size" type="radio">
                                <label for="size-1">Kitten</label>
                            </div>
                            <div class="checkbox">
                                <input id="size-2" name="size" type="radio">
                                <label for="size-2">Cat</label>
                            </div>
                            <div class="checkbox">
                                <input id="size-3" name="size" type="radio">
                                <label for="size-3">Old fart</label>
                            </div>
                        </div>
                    </div>

                    <!-- Color -->
                    <div class="mt-4">
                        <small class="d-block font-weight-bold text-dark mb-2">Color:</small>
                        <div class="d-flex">
                            <div class="custom-color">
                                <input id="color-1" name="size" type="radio">
                                <label for="color-1" class="rounded-circle" style="background: #59ad46;"></label>
                            </div>
                            <div class="custom-color">
                                <input id="color-2" name="size" type="radio">
                                <label for="color-2" class="rounded-circle" style="background: #04050a;"></label>
                            </div>
                            <div class="custom-color">
                                <input id="color-3" name="size" type="radio">
                                <label for="color-3" class="rounded-circle" style="background: #62aedd;"></label>
                            </div>
                            <div class="custom-color">
                                <input id="color-4" name="size" type="radio">
                                <label for="color-4" class="rounded-circle" style="background: #e84385;"></label>
                            </div>
                        </div>
                    </div>

                    <!-- Quantity -->
                    <div class="mt-4">
                        <div class="d-flex">
                            <%= link_to 'Add to cart', cart_products_path(product_id: @product.id), :method => :post,:class => "btn btn-primary ml-3"  %>
                        </div>
                    </div>

                    <!-- Product info -->
                    <div class="mt-4">
                        <small class="d-block font-weight-bold text-dark">Maintaining</small>
                        <ul class="list-unstyled list-icon">
                            <li class="text-sm py-1">
                                <i class="fas fa-tshirt mr-3"></i>Exterior: 98% Furr, 2% Claws
                            </li>
                            <li class="text-sm py-1">
                                <i class="fas fa-air-freshener mr-3"></i>Try not to put your cat in the laundry machine too often, manual wash prefered
                            </li>
                            <li class="text-sm py-1">
                                <i class="fas fa-charging-station mr-3"></i>Iron up to 110&deg;C/230&deg;F
                            </li>
                        </ul>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

<section class="slice slice-lg delimiter-top" id="sct-suggested-products">
    <div class="container">
        <div class="mb-md text-center">
            <h5>Suggested products</h5>
            <div class="fluid-paragraph text-center mt-2">
                <p class="lead lh-180">Check out these special products that we think you might like</p>
            </div>
        </div>
        <div class="row">
        <% 4.times do %>
            <% product = @products.sample %>
                <div class="col-lg-3 col-sm-6 mb-5">
                    <div class="card card-product no-border shadow shadow--hover">
                        <div class="card-image">
                            <%if product.avatar.attached?%>
                                <%= link_to product_path(product.id) do  %>
                                    <%= image_tag product.avatar, alt: 'cat', height: 210, width: 208 %>
                                <% end %>
                            <%else%>
                                <%= link_to product_path(product.id) do %>
                                    <%= image_tag "/assets/img/brand/logo_1.png", alt: "Image placeholder", :class => "img-fluid" %>
                                <% end %>
                            <% end %>
                        </div>
                        <div class="card-body pt-0 text-center">
                            <a href="shop-product.html" class="card-title"><%= product.title %></a>
                            <span class="card-price">$<%= product.price %> USD</span>
                            <div class="product-colors mt-3">
                                <a href="#" style="background-color: #59ad46;" data-toggle="tooltip" data-original-title="Green"></a>
                                <a href="#" style="background-color: #04050a;" data-toggle="tooltip" data-original-title="Black"></a>
                                <a href="#" style="background-color: #62aedd;" data-toggle="tooltip" data-original-title="Blueish"></a>
                                <a href="#" style="background-color: #e84385;" data-toggle="tooltip" data-original-title="Pink"></a>
                            </div>
                        </div>
                        <div class="card-product-actions" data-animation-in="slideInLeft" data-animation-out="slideOutLeft">
                            <button type="button" class="btn-product-action" data-toggle="tooltip" data-original-title="Add to cart">
                                <i class="fas fa-shopping-bag"></i>
                            </button>
                            <button type="button" class="btn-product-action" data-toggle="tooltip" data-original-title="Wishlist">
                                <i class="fas fa-heart"></i>
                            </button>
                        </div>
                    </div>
                </div>
            <%end%>
        </div>
    </div>
</section>