config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'}

  resources :products, :path=> "cats" do
    resources :products_avatars, only: [:create]
  end

  resources :users, :path=> "friends", only: [:show, :edit, :update] do
      resources :avatars, only: [:create]
  end

  namespace :admins do
    resources :admin, only: [:index]
    resources :users
    resources :products
    root to: "admin#index"
  end

  resources :carts, only: [:destroy, :create, :update, :show]
  resources :orders,  only: [:index, :create]

  resources :cart_products
  root 'home#index'
  get 'contact', to: 'home#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_one :order
  has_many :cart_products
  has_many :products, through: :cart_products
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  belongs_to :order, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :cart
  validates :cart, presence: true
  validates :user, presence: true
  after_create :confirm_order
  after_create :confirm_order_admin
  
  def confirm_order
    UserMailer.order_email(self).deliver_now
  end

  def confirm_order_admin
    UserMailer.order_email_admin(self).deliver_now
  end

end

app/models/product.rb
class Product < ApplicationRecord
  validates :price,
        presence: true,
        numericality: {greater_than: 0}
  validates :title,
        presence: true,
        length: { in: 3..30, message: "must be between 3 and 30 characters" }
  validates :description,
        presence: true,
        length: {in: 15..600, message: "must be between 20 and 600 characters"}


  has_many :cart_products, dependent: :destroy
  has_one_attached :avatar
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send



  has_one :cart
  has_many :orders
  has_one_attached :avatar

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def name
    if self.first_name && self.last_name
      self.first_name + " " + self.last_name
    else
      self.first_name
    end
  end
end

app/controllers/avatar_controller.rb
class AvatarController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))

  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_action :correct_user

  # GET /carts
  # GET /carts.json

  # GET /carts/1
  # GET /carts/1.json

  def index
    @user = User.find(params[:user_id])
    @cart = @user.cart
  end

  def show
    @cart = Cart.find(params[:id])
    @total = 0
    @cart.products.each do |product|
      @total += product.price
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:user_id, :product_id, :purchased)
    end

    def correct_user
      if current_user.cart != @cart
        flash[:danger] = "Incorrect cart"
        redirect_to '/'
      end
    end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  layout "application"
  def index
    @orders = current_user.orders
  end

  def create
    @cart = current_user.cart
    @total = 0
    @cart.products.each do |product|
    @total += product.price
    end

  

    @order = Order.new(user_id: current_user.id, total_price: @total)

    # Amount in cents
    @amount = @total*100

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount.to_i,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })
    @order.cart = @cart
    
    if @order.save
      @cart.update(user_id: nil)  
      flash[:notice] = "order pass successfully"
      redirect_to root_path
    else 
      flash.now[:error] = "problem with your order"
      render "carts/show"
    end


    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to cart_path(@cart)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :good_user?, only: [:show, :edit, :update]

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :user_name, :description, :email)
    end

    def good_user?
      if @user != current_user
        flash[:danger] = "You do not have access to other user account"
        redirect_to root_path
      end
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatar_helper.rb
module AvatarHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/new.html.erb
<%= form_tag new_user_cart_charge_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/layouts/_flashes.html.erb
<%flash.each do |name,msg|%>
    <% name = "success" if name == "notice" %>
    <% name = "danger" if name == "alert" %>

    <div id="flash-alert" class="alert alert-<%=name%> alert-dismissible   mb-0" role="alert">
        <h4>Alert</h4>
        <p><%= raw(msg)%></p>
        <button id="alert-btn" type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
 <footer class="footer footer-light bg-white">
        <div class="container">
            <div class="row pt-md">
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <%= link_to root_path do  %>
                        <img src="/assets/img/logo-1.png" alt="Footer logo" width="250" height="100">
                    <% end %>
                    <p class="text-sm">a unique and beautiful photo collection of kitten, you will fall for our little ball of hair too cute.</p>
                </div>
                <div class="col-lg-2 col-6 col-sm-4 ml-lg-auto mb-5 mb-lg-0 align-self-center">
                    <h6 class="heading mb-3">Account</h6>
                    <ul class="list-unstyled">
                    </ul>
                </div>
                <div class="col-lg-2 col-6 col-sm-4 mb-5 mb-lg-0 align-self-center">
                    <h6 class="heading mb-3 margin-bottom:0">About</h6>
                    <ul class="list-unstyled text-small">



                 </ul>
                </div>
                <div class="col-lg-2 col-sm-4 mb-5 mb-lg-0 align-self-center">
                    <h6 class="heading mb-3">Company</h6>
                    <ul class="list-unstyled">

                    </ul>
                </div>
            </div>
            <div class="row align-items-center justify-content-md-between py-4 mt-4 delimiter-top">
                <div class="col-md-6">
                    <div class="copyright text-sm font-weight-bold text-center text-md-left">
                        &copy; 2018 <a class="font-weight-bold" target="_blank">TKP</a>. All rights reserved.
                    </div>
                </div>
                <div class="col-md-6">
                    <ul class="nav justify-content-center justify-content-md-end mt-3 mt-md-0">
                        <li class="nav-item">
                            <a class="nav-link" target="_blank">
                                <i class="fab fa-dribbble"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" target="_blank">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <%= link_to "<i class='fab fa-github'></i>".html_safe, "https://github.com/Ljulienng/thp_kitties", :class => "nav-link", :target => "_blank" %>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link" target="_blank">
                                <i class="fab fa-facebook"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

app/views/layouts/_menu-hamburger.html.erb
    <!--START-->

    <div class="dropdown-principal dropdown">
        <button class="btn btn-outline-primary dropdown-toggle" type="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-bars"></i>
        </button>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
        </div>
    </div>

    <!--END-->

app/views/layouts/_modale.html.erb
<div id="modale" class="collapse fixed-top h-100", style="background: rgba(0, 0, 0, 0.6);">
    <div class="row justify-content-center ">
        <div class="col-lg-5 text-center py-4 bg-white shadow-lg">

            <div id="insidemodale" class="col-8 offset-2">
            
            </div>
        </div>
        <a href="#" id="closemodale" class="far fa-times-circle fa-2x"></a>

    </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-main navbar-expand-lg navbar-sticky navbar-transparent navbar-dark bg-dark" id="navbar-main">
    <div class="container">
        <%= link_to root_path, :class => 'navbar-brand mr-lg-5' do  %>
            <img alt="Image placeholder" src="/assets/img/logo-1.png" style="height: 50px;">
        <% end %>
        <button id="toggler-nav-bar" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-main-collapse" aria-controls="navbar-main-collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar-main-collapse">
            <ul class="navbar-nav align-items-lg-center">
                <li class="nav-item ">
                    <%= link_to 'Shop', products_path, :class => 'nav-link'  %>
                </li>
                    <%= link_to "Contact", contact_path, :class => 'nav-link'  %>
                </li>
            </ul>

            <ul class="navbar-nav align-items-lg-center ml-lg-auto">
                <% if user_signed_in? %>
                    <div class="nav-item dropdown dropdown-animate" data-toggle="hover">
                        <button class="btn btn-white btn-icon-only rounded-circle dropdown" type="button" id="dropdown_user_account" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="btn-inner--icon">
                                <i class="fas fa-user"></i>
                            </span>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdown_user_account">
                            <h6 class="dropdown-header">User menu</h6>

                            <% if current_user.cart %>
                                <%= link_to cart_path(current_user.cart.id), class: "dropdown-item" do %>
                                        <span class="float-right badge badge-primary"><%= current_user.cart.products.count %></span>
                                    <i class="fas fa-shopping-cart text-primary "></i>cart
                                <% end %>
                            <% else %>
                                <%= link_to cart_path(current_user.cart.id), class: "dropdown-item" do %>
                                    <i class="fas fa-shopping-cart text-primary "></i>cart
                                <% end %>

                                    <% end %>
                                    <%= link_to "<i class='fas fa-cog text-primary'></i>Settings".html_safe, edit_user_path(current_user.id), class: "dropdown-item" %>
                                    <%= link_to orders_path, class: "dropdown-item"  do%>
                                            <i class="fas fa-credit-card mr-2 text-primary"></i>
                                            <span>Billing</span>
                                    <% end %>
                                    <% if current_user.try(:admin?) %>
                                        <%= link_to admins_root_path, class: "dropdown-item" do%>
                                            <i class="fas fa-tachometer-alt mr-2 text-primary"></i>
                                            <span>Dashboard</span>
                                        <% end %>
                                    <% end %>

                            <div class="dropdown-divider" role="presentation"></div>
                            <%= link_to "<i class='fas fa-sign-out-alt text-primary'></i>Sign out".html_safe, destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                        </div>
                    </div>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Log in", new_user_session_path, remote: true, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Sign up", new_user_registration_path, remote: true,  class: "nav-link" %>
                    </li>
                <% end %>
            </ul>

        </div>
    </div>
 </nav>

app/views/layouts/_progress.html.erb
<% if user_signed_in? %>
  <% if @progress_status < 100 %>
    <div class="progress-wrapper mt-0 pt-0">
        <div class="progress mb-0" style="height: 30px;">
            <div class="progress-bar bg-success" role="progressbar" style="width: <%= @progress_status %>%;" aria-valuenow="<%= @progress_status %>" aria-valuemin="0" aria-valuemax="100">
              <%= link_to edit_user_path(current_user.id) do  %>
              Profile completed at <strong><%= @progress_status %>%</strong>
              <% end %>
            </div>
        </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TKP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>




    <%=render "layouts/modale"%>


    <%= render "layouts/nav"%>
    <%= render "layouts/progress" %>
    <%= render "layouts/flashes"%>

      <%= yield %>
    <%= render "layouts/footer"%>




  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/orders.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>